# Generated by Django 5.0.6 on 2024-06-17 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id', 'rank'),
            },
        ),
        migrations.CreateModel(
            name='BlogPostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rank', models.IntegerField(default=0)),
                ('blogpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swapp.blogpost')),
            ],
            options={
                'ordering': ('rank', 'id'),
            },
        ),
    ]
