# Generated by Django 5.0.6 on 2024-06-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0002_remove_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
