# Generated by Django 5.0.6 on 2024-06-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0004_blogpost_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-id', '-date')},
        ),
    ]
