# Generated by Django 5.0.6 on 2024-06-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0005_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-rank', '-date')},
        ),
    ]
