# Generated by Django 5.0.6 on 2024-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0008_blogpostphoto_embed_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
