# Generated by Django 5.0.6 on 2024-07-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0009_alter_blogpost_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(),
        ),
    ]
