# Generated by Django 5.0.6 on 2024-07-04 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0010_alter_blogpost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rank', models.IntegerField(default=0)),
                ('blogpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swapp.blogpost')),
            ],
            options={
                'ordering': ('rank', 'id'),
            },
        ),
    ]
