# Generated by Django 5.0.6 on 2024-07-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0011_photobatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='swapp.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
