# Generated by Django 5.0.6 on 2024-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0012_batchupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchupload',
            old_name='blogpost',
            new_name='blog_post',
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
