# Generated by Django 5.0.6 on 2024-07-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0013_rename_blogpost_batchupload_blog_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchupload',
            options={'ordering': ['rank', 'id']},
        ),
        migrations.RenameField(
            model_name='batchupload',
            old_name='blog_post',
            new_name='blogpost',
        ),
        migrations.RemoveField(
            model_name='batchupload',
            name='order',
        ),
        migrations.AddField(
            model_name='batchupload',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
