# Generated by Django 5.0.6 on 2024-07-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0014_alter_batchupload_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photobatch',
            name='blogpost',
        ),
        migrations.DeleteModel(
            name='BatchUpload',
        ),
        migrations.DeleteModel(
            name='PhotoBatch',
        ),
    ]
