# Generated by Django 5.0.6 on 2024-07-06 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0015_remove_photobatch_blogpost_delete_batchupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBatchUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('rank', models.IntegerField(default=0)),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='swapp.blogpost')),
            ],
            options={
                'ordering': ('rank', 'id'),
            },
        ),
    ]
