# Generated by Django 5.0.6 on 2024-07-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0016_photobatchupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoBatchUpload',
        ),
    ]
