# Generated by Django 5.0.6 on 2024-07-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0018_photobatchupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostphoto',
            name='image',
        ),
    ]
